[wokwi]
version = 1
firmware = ".pio/build/esp32dev/firmware.bin"
elf = ".pio/build/esp32dev/firmware.elf"

# Reenvía http://localhost:8180 de tu Mac al puerto 80 del ESP32 simulado
[[net.forward]]
from = "localhost:8180"
to = "target:80"
